/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "Pin_3.h"
#include "Pin_3_aliases.h"
#include "Pin_4.h"
#include "Pin_4_aliases.h"
#include "Pin_5.h"
#include "Pin_5_aliases.h"
#include "UartPC.h"
#include "UartPC_SPI_UART.h"
#include "UartPC_PINS.h"
#include "UartPC_SPI_UART_PVT.h"
#include "UartPC_PVT.h"
#include "UartPC_BOOT.h"
#include "UartPC_SCBCLK.h"
#include "UartPC_tx.h"
#include "UartPC_tx_aliases.h"
#include "UartPC_rx.h"
#include "UartPC_rx_aliases.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

